name: Callerworkflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'user name'
        required: false
        type: string

jobs:
  gitHub-actions-demo:
    uses: srdeekon/demo-reusable/.github/workflows/calledworkflow.yaml@main
  
